### PR TITLE
Add toggle animation to navbar

### PR DESCRIPTION
**Pull request by alllenshibu**
**Demo Video**
https://user-images.githubusercontent.com/93600615/179961225-8452f991-5e02-4e65-9b6b-dbbc5eb70b22.mp4

### CODE REVIEW

**Comment by alapanoski** [comment]
**Demo Video**

https://user-images.githubusercontent.com/93600615/179907613-5c815c42-ed8e-4ebc-9ba4-b5d5e3b36463.mp4

**Comment by aldrinjenson** [comment]
Hey, thanks for this PR✨

**Comment by aldrinjenson** [comment]
@alanphil2k01 and @amaldevcd  ,please take a look at the changes when free.

**Comment by alanphil2k01** [comment]
@alapanoski the nav.css you added had to be removed as it hid the navbar in desktop view. Can you make the necessary changes so the css would run only in mobile view. Also what was the purpose of the anatole-header.js file as it is not being imported in params.toml.

**Comment by alllenshibu** [comment]
I have made the necessary changes to nav.css to make it run only in mobile view.

`assets/js/anatole-header.js` is used to override the `anatole-header.js` file provided by the anatole theme. This is required because the original `anatole-header.js` file unnecessarily adds `nav--active` class to hamburger menu which moves it under the opened navbar rendering it useless.

**Without `anatole-header.js`**
https://user-images.githubusercontent.com/93600615/182034254-af468e44-5780-48b9-b35c-4e61762210bb.mp4

**With `anatole-header.js`**
https://user-images.githubusercontent.com/93600615/182034272-0ea0acb0-0b8f-4025-a475-626f2dc2ac6c.mp4

`anatole-header.js` does not require to be imported in `params.toml` as the folder structure is set up in such a way that Hugo overwrites the file originally provided by the anatole theme.

**Pull request merged**
